services:
  back-api:
    container_name: gest-edu-back-api
    build: .
    image: gest-edu-back-api
    ports:
      - 8080:8080
    environment:
      DB_URL: ${DB_URL}
      DB_USER_NAME: ${DB_USER_NAME}
      DB_PASSWORD: ${DB_PASSWORD}
      MAIL_USER_NAME: ${MAIL_USER_NAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
    restart: always
    depends_on:
      - db
  front:
    build: ../gest-edu-front
    image: gest-edu-front
    ports:
      - 3000:3000
    environment:
      BACK_API: "https://back-api:8443/gest-edu/api"
      NODE_TLS_REJECT_UNAUTHORIZED: 0
      REACT_APP_BLANK_PROFILE_PICTURE: "https://firebasestorage.googleapis.com/v0/b/gestedu2024.appspot.com/o/defaultUserImage.png?alt=media&token=72b03305-8f00-4aff-bde0-7964ab3046c0"
    depends_on:
      - back-api
  db:
    container_name: gest-edu-db
    image: postgres:16.3
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${DB_USER_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data: