services:
  gest-edu-back-api:
    container_name: gest-edu-back-api
    build: .
    ports:
      - 8080:8080
    environment:
      DB_URL: ${DB_URL}
      DB_USER_NAME: ${DB_USER_NAME}
      DB_PASSWORD: ${DB_PASSWORD}
    restart: always
    depends_on:
      - db
  db:
    container_name: gest-edu-db
    image: postgres:16.3
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${DB_USER_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data: